name: Magia
favicon: null
layout_spectrum: 0.16349196364171803
typography_spectrum: 0.6954711368307471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2805132777430117
  lightness: 0.6481514966581017
  saturation: 0.1780914084520191
  rhythmicContrast: 0.05677687586285174
purpose: []
